services:
  - type: web
    name: organizador-finanzas
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: organizador-finanzas-db
          property: connectionString

databases:
  - name: organizador-finanzas-db
